# Generated by Django 5.1 on 2024-08-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='extras',
            field=models.ManyToManyField(blank=True, related_name='departamentos', to='web.extra'),
        ),
    ]
